### ISSUE TITLE
YouTube Gaming compat?

### ISSUE THREAD

**Issue by chuckreynolds** [macbookandrew/wp-youtube-live#1]
Just throwing the idea out that some may want this for `gaming.youtube.com` streams… be nice if this plugin could also handle that subdomain.

(_I'm aware that youtube.com/video-url and gaming.youtube.com/video-url are the same for streams… but knowing a lot of streamers; they want their stats to be on the gaming subdomain_)

**Comment by macbookandrew** [comment]
@chuckreynolds I have no problem adding support for it, but where would it need the subdomain? Just in the link shown if no video is available? or the embedded video as well?

**Comment by chuckreynolds** [comment]
@macbookandrew just looking at this line: https://github.com/macbookandrew/wp-youtube-live/blob/master/inc/EmbedYoutubeLiveStreaming.php#L155

I'm assuming only the embed url needs to be gaming.yout... I just know guys that post videos to gaming channels and want the stats for those videos to show up as a gaming.youtube.com view instead of normal youtube.com view. Just segregation of analytics.

**Comment by macbookandrew** [comment]
@chuckreynolds Just released [v1.5.1](https://github.com/macbookandrew/wp-youtube-live/releases/tag/v1.5.1), which includes an option for this feature.

Thanks for the suggestion!
