### ISSUE TITLE
Restrict API?

### ISSUE THREAD

**Issue by glen4cindy** [macbookandrew/wp-youtube-live#13]
I didn't see this mentioned in the documentation.

Is it necessary to worry about restricting this? Is it likely that someone would hijack and use my API key?

If I do need to add a restriction would it be the HTTP one?

Thanks in advance.

**Comment by macbookandrew** [comment]
Probably not took likely, but it’s possible, and if you have payment enabled, you definitely don’t want someone running up a bill for you.

Because the server is making the request, you’d want the IP restriction; set it to the IP address of your server.
