### ISSUE TITLE
[Feature request] Manual trigger URL admin/editor can visit to set off a fetch of YouTube API

### ISSUE THREAD

**Issue by HongPong** [macbookandrew/wp-youtube-live#14]
Hi,

I would like to request a feature where an authenticated administrator / editor user, can visit a special URL on their browser, which would trigger an immediate fetch of the channel state from YouTube (instead of waiting for 15 minutes to conserve quota). This way someone managing WP and live video can kick off the process by hand. The interface could also be a button but I think an admin/editor visiting a trigger URL would be optimal.

I might be able to program this myself - I could look into it in the next couple weeks.

Thanks for this interesting plugin, looking forward to really getting into how it works.

**Comment by macbookandrew** [comment]
@HongPong Added in the latest release a button to flush the cache, so the next request will fetch fresh data; see screenshot of the admin:

![Screen Shot 2020-07-07 at 21 23 51](https://user-images.githubusercontent.com/784333/86867458-75ac2780-c098-11ea-9f29-ae75e96dd089.png)

**Comment by HongPong** [comment]
That is so cool cheers!!
