### ISSUE TITLE
 how do I solve this of hide this ?

### ISSUE THREAD

**Issue by carlucci9660** [macbookandrew/wp-youtube-live#15]
![image](https://user-images.githubusercontent.com/31194015/122313986-4f684c00-cee5-11eb-9fc0-fe42a0234ad0.png)

how do I solve this of hide this ?

**Comment by macbookandrew** [comment]
@carlucci9660 It looks like you have debugging enabled in the plugin settings; if you disable it, those errors should disappear.

As for the errors themselves: 1.7.19 should fix the problem with the referer being blocked, thanks to @d2roth!
