### ISSUE TITLE
Uncaught TypeError on trying to active the Plugin

### ISSUE THREAD

**Issue by real-napster** [macbookandrew/wp-youtube-live#17]
Hey Guys,

when i try to activate the Plugin on my WordPress Instance the following Error occurs:

`Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, bool given in /var/www/vhosts/xx.net/httpdocs/wp-content/plugins/wp-youtube-live/wp-youtube-live.php:267 Stack trace: #0 /var/www/vhosts/xx.net/httpdocs/wp-includes/class-wp-hook.php(303): wp_ytl_plugin_activation('') #1 /var/www/vhosts/xx.net/httpdocs/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array) #2 /var/www/vhosts/xx.net/httpdocs/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #3 /var/www/vhosts/xx.net/httpdocs/wp-admin/plugins.php(193): do_action('activate_wp-you...') #4 {main} thrown in /var/www/vhosts/xx.net/httpdocs/wp-content/plugins/wp-youtube-live/wp-youtube-live.php on line 267`

WordPress: 5.8.3
PHP: 8.0
Webserver: nginx

can someone help me with this?

thanks
real-napster

**Comment by macbookandrew** [comment]
@real-napster https://github.com/macbookandrew/wp-youtube-live/commit/1814c92179cf4dd7b8314828a7fc55fa9191bb7f should fix it for you; it’s released as 1.7.21 on the WordPress.org plugin repository.

**Comment by real-napster** [comment]
Works like a charme! Thanks!
