### ISSUE TITLE
Auto load recent video / playlist?

### ISSUE THREAD

**Issue by TripleFFFRadio** [macbookandrew/wp-youtube-live#2]
Hi! Is there any planned functionality for video playback when the stream is offline, either most recent or from a playlist? Another plugin claims to do this, but their support forum appears to be abandoned :)

**Comment by macbookandrew** [comment]
@TripleFFFRadio Just added support for a fallback video or a “channel player” showing all of your recent videos. When you get a chance, could you [download from GitHub](https://github.com/macbookandrew/wp-youtube-live/archive/v1.6.1.zip) and try it out?

**Comment by reporti** [comment]
Hi Andrew is there a way the YouTube live can auto embedded the current YouTube live . I tried to do live stream but the recent video is showing  even I refreshed the page not coming up the current live YouTube feed thanks

**Comment by macbookandrew** [comment]
@reporti Could you post in the WP support forums instead please? Please include a link to the page with your player.
