### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by hasanmisbah** [macbookandrew/wp-youtube-live#3]
it showing error on frontend value
`Notice: Undefined index: isAjax in /home/.........../public_html/tv/wp-content/plugins/wp-youtube-live/wp-youtube-live.php on line 126
Notice: Undefined index: isAjax in /home/.........../public_html/tv/wp-content/plugins/wp-youtube-live/wp-youtube-live.php on line 80
Notice: Undefined index: isAjax in /home/.........../public_html/tv/wp-content/plugins/wp-youtube-live/wp-youtube-live.php on line 81
Notice: Undefined index: isAjax in /home/.........../public_html/tv/wp-content/plugins/wp-youtube-live/wp-youtube-live.php on line 82
Notice: Undefined variable: youtube_options in /home/.........../public_html/tv/wp-content/themes/my_themes_name/functions.php on line 10`

Channel URL doesn't include the channel URL. it showing `https://youtube.com/channel/`

I've added this filter in my theme functions php file
`add_filter( 'wp_youtube_live_no_stream_available', 'my_ytl_custom_message' );
function my_ytl_custom_message( $message ) {
    $message = '<p>Please check back later or subscribe to <a target="_blank" href="https://youtube.com/channel/' . $youtube_options['youtube_live_channel_id'] . '">our YouTube channel</a>.</p>
    <p><button type="button" class="button" id="check-again">Check again</button><span class="spinner" style="display:none;"></span></p>';
    return $message;
}`

and
`add_filter( 'wp_youtube_live_transient_timeout', 'my_ytl_custom_timeout' );
function my_ytl_custom_timeout( $message ) {
    return '15';
}`

**Comment by macbookandrew** [comment]
@hasanmisbah You don’t need to add those filters to your `functions.php` unless you want to modify the output.

Can you double-check that you have an API key and channel ID set in the YouTube Live Settings page?

**Comment by hasanmisbah** [comment]
Yeah, I've checked API settings page. more time. and it has no problem.
i also removed code from functions.php file. now the output is 
`Notice: Undefined index: isAjax in /home/............./public_html/tv/wp-content/plugins/wp-youtube-live/wp-youtube-live.php on line 80
Notice: Undefined index: isAjax in /home/............./public_html/tv/wp-content/plugins/wp-youtube-live/wp-youtube-live.php on line 81
Notice: Undefined index: isAjax in /home/............./public_html/tv/wp-content/plugins/wp-youtube-live/wp-youtube-live.php on line 82
Notice: Undefined index: isAjax in /home/............./public_html/tv/wp-content/plugins/wp-youtube-live/wp-youtube-live.php on line 126`

I've added fallback video it works. showing this notice on the frontend.

**Comment by macbookandrew** [comment]
Try updating to the latest version of the plugin.

Andrew Minion | Web Developer
andrew@andrewrminion.com | 704-769-0625

**Comment by hasanmisbah** [comment]
I've cloned latest version from this repo.

**Comment by macbookandrew** [comment]
Since yesterday afternoon?

Andrew Minion | Web Developer
andrew@andrewrminion.com | 704-769-0625

**Comment by hasanmisbah** [comment]
yeah i've updated now and got new error
`Notice: Undefined property: stdClass::$error in /home/......................./public_html/tv/wp-content/plugins/wp-youtube-live/inc/EmbedYoutubeLiveStreaming.php on line 162`

**Comment by macbookandrew** [comment]
@hasanmisbah Can you [download and try this](https://github.com/macbookandrew/wp-youtube-live/archive/master.zip) minor update?

**Comment by hasanmisbah** [comment]
yeah, i updated. and the problem is now solved. thanks for your faster response and update.

**Comment by macbookandrew** [comment]
Great; thanks!
