### ISSUE TITLE
Always using 640x320 dimension

### ISSUE THREAD

**Issue by ajshakib** [macbookandrew/wp-youtube-live#6]
The plugin is using 640x320 dimension without showing the video in the width and height I entered. Please help me to fix it.

**Comment by macbookandrew** [comment]
Sounds like your theme stylesheet may be overriding the embed’s specified width/height. Please check that and modify if necessary.

**Comment by ajshakib** [comment]
I tried on different site with a different theme... But the result was same... Please check this image...
[https://i.imgur.com/rRAmx4s.png](https://i.imgur.com/rRAmx4s.png)

**Comment by macbookandrew** [comment]
Can you enable debugging in the plugin settings and copy/paste the debugging comment, or send me a screenshot of at least these parts of the debugging info? https://images.andrewrminion.com/file/ARMD-images/YouTube-live-stream-debugging-embed-size.png

Also, have you tried disabling other plugins and using one of the default WordPress themes?

**Comment by gpearre** [comment]
Was this resolved?  I'm seeing the same issue.  It's making my site non-responsive to mobile/tablets.
