### ISSUE TITLE
Content width change when OFFLINE and STREAMING

### ISSUE THREAD

**Issue by kilimats** [macbookandrew/wp-youtube-live#9]
Are you aware on this issue where the website width change when the plugin is OFFLINE or STREAMING as pictured below. Any idea what is causing the page to shrink like that when the plugin is OFFLINE?

Streaming width
https://i.imgur.com/uUOvRhJ.png

Offline width
https://i.imgur.com/VlcJ9XH.png

**Comment by macbookandrew** [comment]
@kilimats No, I wasn’t aware of it. Sounds like the `iframe` is wider than the no-content message. I’d recommend you use CSS to set a width on the left column so it doesn’t shrink when the video is live.

**Comment by macbookandrew** [comment]
I’d need a link to the site to be able to suggest anything.

**Comment by kilimats** [comment]
Oups my bad, here is a link https://www.tradoto.com/livestream/

**Comment by macbookandrew** [comment]
Sorry, I don’t have any ideas on it. You’d have to talk to your web developer and have them adjust it, or the theme author and see if they have any ideas.
